export const products = [
    {
        _id: "123456",
        name: "Дверь мет. 11см ISOTERMA серебро царга Лиственница беж 960мм правая",
        availability: "В наличии",
        price: 32200,
        unit: "шт",
        rate: 4.5,
        brand: "Кайзер",
        material: "Металл",
        color: "Темный металл",
        category: "Двери",
        subcategory: "Входные двери"
    },
    {
        _id: "220229",
        name: "Дверь мет. 7,5 см Гарда Серебро Астана милки Царга (860мм правая/Ф1)",
        availability: "Под заказ",
        price: 19800,
        unit: "шт",
        rate: 4.4,
        brand: "Кайзер",
        material: "Металл",
        color: "Темный металл",
        category: "Двери",
        subcategory: "Входные двери"
    },
    {
        _id: "347761",
        name: "Дверь мет. 9 см Серебро Зеркало Эмалит белый ФЛЗ-13 (960мм) правая/Ф1",
        availability: "В наличии",
        price: 22800,
        unit: "шт",
        rate: 4.1,
        brand: "Кайзер",
        material: "Металл",
        color: "Темный металл",
        category: "Двери",
        subcategory: "Входные двери"
    },
    {
        _id: "899257",
        name: "Дверь SCHLAGER Ralf 5/1 (700мм, ПГ, 2000мм, 38мм, текстурированная бумага, венге светлый)",
        availability: "В наличии",
        price: 4500,
        unit: "шт",
        rate: 3.9,
        brand: "SCHLAGER",
        material: "Дерево",
        color: "Венге светлый",
        category: "Двери",
        subcategory: "Межкомнатные двери"
    },
    {
        _id: "991670",
        name: "Дверь VELLDORIS LINEA 6 ДО 600*2000 Экошпон Дуб Серый поперечный, ст Лакобель черное",
        availability: "В наличии",
        price: 4725,
        unit: "шт",
        rate: 4.9,
        brand: "VELLDORIS",
        material: "Дерево",
        color: "Дуб Серый",
        category: "Двери",
        subcategory: "Межкомнатные двери"
    },
    {
        _id: "290474",
        name: "ОЛОВИ Дверное полотно 700х2000мм Белое Гост окрашен з 2014",
        availability: "В наличии",
        price: 4650,
        unit: "шт",
        rate: 4.8,
        brand: "Олови",
        material: "Дерево",
        color: "Белый",
        category: "Двери",
        subcategory: "Межкомнатные двери"
    },
    {
        _id: "430368",
        name: "Панель MDF Кроностар- Вишня 026 250*2600*7 (6шт.)",
        availability: "В наличии",
        price: 270,
        unit: "шт",
        rate: 4.3,
        brand: "Кроностар",
        material: "МДФ",
        color: "Вишня",
        category: "Панели",
        subcategory: "Панели МДФ"
    },
    {
        _id: "996215",
        name: "Панель MDF Классик Груша 238*2600*6 (8 шт.)",
        availability: "В наличии",
        price: 322,
        unit: "шт",
        rate: 4.4,
        brand: "Классик",
        material: "МДФ",
        color: "Груша ",
        category: "Панели",
        subcategory: "Панели МДФ"
    },
    {
        _id: "949216",
        name: "Панель MDF Классик Сосна светлая 238*2600*6 (8 шт.)",
        availability: "В наличии",
        price: 322,
        unit: "шт",
        rate: 4.6,
        brand: "Классик",
        material: "МДФ",
        color: "Сосна",
        category: "Панели",
        subcategory: "Панели МДФ"
    },
    {
        _id: "717387",
        name: "Панель MDF Классик Клен 238*2600*6 (8шт)",
        availability: "В наличии",
        price: 322,
        unit: "шт",
        rate: 4.6,
        brand: "Классик",
        material: "МДФ",
        color: "Клен",
        category: "Панели",
        subcategory: "Панели МДФ"
    },
    {
        _id: "429965",
        name: "Пласт.вагонка белая (3м х 0.1м), 1уп.=20шт. 10мм толщина",
        availability: "В наличии",
        price: 128,
        unit: "шт",
        rate: 4.6,
        brand: "Альта-Профиль",
        material: "ПВХ",
        color: "Белый",
        category: "Панели",
        subcategory: "Панели ПВХ(вагонка)"
    },
    {
        _id: "400300",
        name: "Пласт.вагонка салатовая (3м х 0.1м), 1уп.=20шт. 10мм толщина",
        availability: "В наличии",
        price: 126,
        unit: "шт",
        rate: 4.5,
        brand: "Альта-Профиль",
        material: "ПВХ",
        color: "Зеленый",
        category: "Панели",
        subcategory: "Панели ПВХ(вагонка)"
    },
    {
        _id: "612933",
        name: "Пласт.вагонка кремовая (3м х 0.1м), 1уп.=20шт. 10мм толщина",
        availability: "В наличии",
        price: 126,
        unit: "шт",
        rate: 4.5,
        brand: "Альта-Профиль",
        material: "ПВХ",
        color: "Кремовый",
        category: "Панели",
        subcategory: "Панели ПВХ(вагонка)"
    },
    {
        _id: "400378",
        name: "Панель Акватон Кирпич цвет желтый (1,22м*2,44м) 6мм",
        availability: "В наличии",
        price: 2020,
        unit: "шт",
        rate: 4.8,
        brand: "АКВАТОН",
        material: "ПВХ",
        color: "Кремовый",
        category: "Панели",
        subcategory: "Панели ПВХ(кирпич)"
    },
    {
        _id: "733104",
        name: `Панель Акватон "Кирпич" цвет белый (1,22м*2,44м) 6мм`,
        availability: "В наличии",
        price: 2020,
        unit: "шт",
        rate: 4.8,
        brand: "АКВАТОН",
        material: "ПВХ",
        color: "Белый",
        category: "Панели",
        subcategory: "Панели ПВХ(кирпич)"
    },
    {
        _id: "395483",
        name: `Панель Акватон "Кирпич" цвет темный (1,22м*2,44м) 6мм`,
        availability: "В наличии",
        price: 2020,
        unit: "шт",
        rate: 4.7,
        brand: "АКВАТОН",
        material: "ПВХ",
        color: "Темный",
        category: "Панели",
        subcategory: "Панели ПВХ(кирпич)"
    },
    {
        _id: "638629",
        name: `Мойка FABIA PROFI врезная 60x50см (3х0,8мм) глуб чаши 200мм, в компл сифон 3,5"+корзина 60503 М`,
        availability: "В наличии",
        price: 16490,
        unit: "шт",
        rate: 5.0,
        brand: "САНАКС",
        material: "Нержавеющая сталь",
        color: "Металл",
        category: "Сантехника",
        subcategory: "Кухонные мойки"
    },
    {
        _id: "573150",
        name: "Мойка EcoStone ES-18-328 (бежевый) односекционная реверсивная с крылом 645х495 мм",
        availability: "В наличии",
        price: 5840,
        unit: "шт",
        rate: 4.0,
        brand: "ECOSTONE",
        material: "Мрамор",
        color: "Бежевый",
        category: "Сантехника",
        subcategory: "Кухонные мойки"
    },
    {
        _id: "753668",
        name: "Мойка EcoStone ES-11-308 (черный) круглая Ф500 мм",
        availability: "В наличии",
        price: 5840,
        unit: "шт",
        rate: 4.0,
        brand: "ECOSTONE",
        material: "Мрамор",
        color: "Черный",
        category: "Сантехника",
        subcategory: "Кухонные мойки"
    },
    {
        _id: "753783",
        name: `Мойка FABIA врезная круглая d49 ЭКОНОМ (0,6 нерж.ст.) гл. чаши 160мм, в компл 3,5"сифон 04906`,
        availability: "В наличии",
        price: 1900,
        unit: "шт",
        rate: 4.4,
        brand: "No-name",
        material: "Нержавеющая сталь",
        color: "Металл",
        category: "Сантехника",
        subcategory: "Кухонные мойки"
    },
    {
        _id: "242670",
        name: "AM.PM F8007111 Like Смеситель для кухни, хром",
        availability: "В наличии",
        price: 5190,
        unit: "шт",
        rate: 4.6,
        brand: "AM.PM",
        material: "Металл",
        color: "Никель",
        category: "Сантехника",
        subcategory: "Смесители для кухни"
    },
    {
        _id: "221299",
        name: "AM.PM F8007100 Like Смеситель для кухни, хром",
        availability: "В наличии",
        price: 4990,
        unit: "шт",
        rate: 4.8,
        brand: "AM.PM",
        material: "Металл",
        color: "Хром",
        category: "Сантехника",
        subcategory: "Смесители для кухни"
    },
    {
        _id: "988350",
        name: "AM.PM F85C02100 Sunny Смеситель для умывальника, хром",
        availability: "В наличии",
        price: 4990,
        unit: "шт",
        rate: 4.8,
        brand: "AM.PM",
        material: "Металл",
        color: "Хром",
        category: "Сантехника",
        subcategory: "Смесители для умывальника"
    },
    {
        _id: "672974",
        name: "AM.PM F85A02122 X-Joy Смеситель для умывальника, черный",
        availability: "В наличии",
        price: 5990,
        unit: "шт",
        rate: 4.7,
        brand: "AM.PM",
        material: "Металл",
        color: "Черный",
        category: "Сантехника",
        subcategory: "Смесители для умывальника"
    },
    {
        _id: "422605",
        name: "Линолеум Томас 1 Дельта ширина 3м Синтерос",
        availability: "В наличии",
        price: 1390,
        unit: "пог.м",
        rate: 3.4,
        brand: "Синтерос",
        material: "Линолеум",
        color: "Серый",
        category: "Напольные покрытия",
        subcategory: "Линолеум"
    },
    {
        _id: "694111",
        name: "Линолеум Сорбона 6 Force ширина 4м Таркетт",
        availability: "В наличии",
        price: 3030,
        unit: "пог.м",
        rate: 3.9,
        brand: "Таркетт",
        material: "Линолеум",
        color: "Коричневый",
        category: "Напольные покрытия",
        subcategory: "Линолеум"
    },
    {
        _id: "139383",
        name: "Линолеум Танго 3 Идиллия Нова ширина 2,0м Tarkett",
        availability: "В наличии",
        price: 2160,
        unit: "пог.м",
        rate: 4.9,
        brand: "Таркетт",
        material: "Линолеум",
        color: "Коричневый",
        category: "Напольные покрытия",
        subcategory: "Линолеум"
    },
    {
        _id: "843707",
        name: "Линолеум Аризона 1 Спринт PRO ширина 3,5м Tarkett",
        availability: "В наличии",
        price: 2921,
        unit: "пог.м",
        rate: 4.4,
        brand: "Таркетт",
        material: "Линолеум",
        color: "Серый",
        category: "Напольные покрытия",
        subcategory: "Линолеум"
    },
    {
        _id: "307032",
        name: "Линолеум Византия 4 Фаворит ширина 3,5м Tarkett",
        availability: "В наличии",
        price: 3505,
        unit: "пог.м",
        rate: 4.8,
        brand: "Таркетт",
        material: "Линолеум",
        color: "Серый",
        category: "Напольные покрытия",
        subcategory: "Линолеум"
    },
    {
        _id: "772674",
        name: "пол лам. WoodStyle Solid Тальк (1380*193*12мм) 33 кл 4V (1,332кв.м/упак)",
        availability: "В наличии",
        price: 1912,
        unit: "упа",
        rate: 4.1,
        brand: "Woodstyle",
        material: "Дерево",
        color: "Серый",
        category: "Напольные покрытия",
        subcategory: "Ламинат"
    },
    {
        _id: "670374",
        name: "Пол лам.EGGER Н2015 Дуб под старину 4V (1292*193*8мм)33кл(1,9948кв.м/уп)",
        availability: "В наличии",
        price: 995,
        unit: "упа",
        rate: 3.9,
        brand: "EGGER",
        material: "Дерево",
        color: "Коричневый",
        category: "Напольные покрытия",
        subcategory: "Ламинат"
    },
    {
        _id: "892077",
        name: "пол лам.Quick Step Creo Plus 5332 Дуб Вирджиния белый 32 кл 4V(190*1200*8мм)(1,596 кв.м/уп)",
        availability: "В наличии",
        price: 2003,
        unit: "упа",
        rate: 4.7,
        brand: "Quik Step",
        material: "Дерево",
        color: "Бежевый",
        category: "Напольные покрытия",
        subcategory: "Ламинат"
    },
    {
        _id: "567372",
        name: "Пол лам. KRONOSTAR SALZBURG Дуб барбикан D 2048 4V (1380х193х10мм) 1,864м2 с фаской",
        availability: "В наличии",
        price: 2138,
        unit: "упа",
        rate: 4.8,
        brand: "Quik Step",
        material: "Дерево",
        color: "Коричневый",
        category: "Напольные покрытия",
        subcategory: "Ламинат"
    },
    {
        _id: "713057",
        name: "60104-08 Mystery Обои виниловые на флизелин. основе горячего тиснения 10,05х1,06, 6 шт/упак",
        availability: "В наличии",
        price: 2720,
        unit: "рул",
        rate: 5.0,
        brand: "Mystery",
        material: "Флизелин",
        color: "Салатовый",
        category: "Обои",
        subcategory: "Обои декоративные"
    },
    {
        _id: "744176",
        name: "60260-04 Tiara обои виниловые на флиз.осн. горячего тиснения 10,05*1,06",
        availability: "В наличии",
        price: 2675,
        unit: "рул",
        rate: 4.7,
        brand: "Эрисманн",
        material: "Флизелин",
        color: "Бежевый",
        category: "Обои",
        subcategory: "Обои декоративные"
    },
    {
        _id: "570057",
        name: "60126-06 Felicita обои виниловые на флиз.осн. горячего тиснения 10,05*1,06",
        availability: "В наличии",
        price: 2162,
        unit: "рул",
        rate: 4.5,
        brand: "Эрисманн",
        material: "Флизелин",
        color: "Белый",
        category: "Обои",
        subcategory: "Обои декоративные"
    },
    {
        _id: "116043",
        name: "7157-23 Обои виниловые на флиз. основе Euro Decor 1,06*10,05 6 рул/уп",
        availability: "В наличии",
        price: 2653,
        unit: "рул",
        rate: 4.4,
        brand: "ЕuroDecor",
        material: "Флизелин",
        color: "Серый",
        category: "Обои",
        subcategory: "Обои декоративные"
    },
    {
        _id: "116042",
        name: "417-01 Обои Палитра HomeColour (25*1,06) виниловые на флизелиновой основе/5шт",
        availability: "В наличии",
        price: 2530,
        unit: "рул",
        rate: 2.4,
        brand: "Палитра",
        material: "Флизелин",
        color: "Серый",
        category: "Обои",
        subcategory: "Обои под покраску"
    },
    {
        _id: "308722",
        name: "3008-01 Обои Палитра (10*1,06) виниловые на флизелиновой основе/5шт",
        availability: "В наличии",
        price: 1080,
        unit: "рул",
        rate: 4.8,
        brand: "Палитра",
        material: "Флизелин",
        color: "Бежевый",
        category: "Обои",
        subcategory: "Обои под покраску"
    },
    {
        _id: "316748",
        name: "Шнур ШВВП 2х0,75 ГОСТ (100м), белый TDM",
        availability: "В наличии",
        price: 20,
        unit: "м",
        rate: 4.4,
        brand: "TDM",
        material: "Многожильный",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Кабели и провода"
    },
    {
        _id: "371361",
        name: "Провод ПВС 3х1,5 ГОСТ (100м), белый TDM",
        availability: "В наличии",
        price: 61,
        unit: "м",
        rate: 4.5,
        brand: "TDM",
        material: "Многожильный",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Кабели и провода"
    },
    {
        _id: "850107",
        name: "Кабель ВВГ-П нг(А)-LS 3х4 ок(N, PE)-0,66 ГОСТ (100м) TDM",
        availability: "В наличии",
        price: 105,
        unit: "м",
        rate: 4.5,
        brand: "TDM",
        material: "Одножильный",
        color: "Черный",
        category: "Электротехническая продукция",
        subcategory: "Кабели и провода"
    },
    {
        _id: "600495",
        name: "Кабель ВВГ-П нг(А)-LS 3х1.5LS ок(N, PE)-0,66 ГОСТ (100м) TDM",
        availability: "В наличии",
        price: 46,
        unit: "м",
        rate: 4.1,
        brand: "TDM",
        material: "Одножильный",
        color: "Черный",
        category: "Электротехническая продукция",
        subcategory: "Кабели и провода"
    },
    {
        _id: "867571",
        name: "Счетчик электроэнергии CE101 R5.1 145 M6 однофазный однотарифный, 5(60), кл.точ. 1.0, DIN-рейка",
        availability: "В наличии",
        price: 1227,
        unit: "шт",
        rate: 4.2,
        brand: "Энергомера",
        material: "Пластик",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Счетчики"
    },
    {
        _id: "609383",
        name: "Бокс ЩРН-П-8(Б) модуля навесн. пластик IР40 TDM с белой крышкой SQ0903-0003",
        availability: "В наличии",
        price: 598,
        unit: "шт",
        rate: 4.3,
        brand: "TDM",
        material: "Пластик",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Щиты, минибоксы"
    },
    {
        _id: "984293",
        name: "Бокс ЩРН-П-3 модуля навесн. пластик IР41 TDM SQ0901-0008",
        availability: "В наличии",
        price: 255,
        unit: "шт",
        rate: 4.4,
        brand: "TDM",
        material: "Пластик",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Щиты, минибоксы"
    },
    {
        _id: "670850",
        name: "Корпус навес ЩРН-12 (265*310*120) TDM SQ0905-0011",
        availability: "В наличии",
        price: 1522,
        unit: "шт",
        rate: 4.4,
        brand: "TDM",
        material: "Металл",
        color: "Белый",
        category: "Электротехническая продукция",
        subcategory: "Щиты, минибоксы"
    },
    {
        _id: "455093",
        name: "Бокс ЩРВ-П-8 модулей встраиваемый пластик IP41, Антрацит TDM",
        availability: "В наличии",
        price: 681,
        unit: "шт",
        rate: 4.4,
        brand: "TDM",
        material: "Пластик",
        color: "Черный",
        category: "Электротехническая продукция",
        subcategory: "Щиты, минибоксы"
    },
    {
        _id: "520127",
        name: "Кер. плитка Элегия верх 300*600 1,62 кв.м/упак",
        availability: "В наличии",
        price: 840,
        unit: "м.к",
        rate: 4.3,
        brand: "AXIMA",
        material: "Керамика",
        color: "Бежевый",
        category: "Плитка",
        subcategory: "Керамическая плитка"
    },
    {
        _id: "862568",
        name: "Кер. плитка Сити темно-серая рельеф 300*600 1,62 кв.м/упак",
        availability: "В наличии",
        price: 912,
        unit: "м.к",
        rate: 4.8,
        brand: "AXIMA",
        material: "Керамика",
        color: "Серый",
        category: "Плитка",
        subcategory: "Керамическая плитка"
    },
    {
        _id: "323828",
        name: "Кер. плитка Мартиника низ 300*600 1,62 кв.м/упак",
        availability: "В наличии",
        price: 912,
        unit: "м.к",
        rate: 4.7,
        brand: "AXIMA",
        material: "Керамика",
        color: "Серый",
        category: "Плитка",
        subcategory: "Керамическая плитка"
    },
    {
        _id: "304274",
        name: "Кер. плитка Калипсо темная 250*500 1,25 кв.м/упак",
        availability: "Под заказ",
        price: 817,
        unit: "м.к",
        rate: 4.0,
        brand: "AXIMA",
        material: "Керамика",
        color: "Голубой",
        category: "Плитка",
        subcategory: "Керамическая плитка"
    },
    {
        _id: "543844",
        name: "Керамогранит Lignum beige PG 01 450*450",
        availability: "Под заказ",
        price: 1100,
        unit: "м.к",
        rate: 5.0,
        brand: "Gracia Ceramica",
        material: "Гранит",
        color: "Коричневый",
        category: "Плитка",
        subcategory: "Керамогранит"
    },
    {
        _id: "561765",
        name: "Керамогранит Beton 60*60 baze antracite глазур 1.44 кв.м./упак",
        availability: "В наличии",
        price: 1448,
        unit: "м.к",
        rate: 4.9,
        brand: "Zerde",
        material: "Гранит",
        color: "Черный",
        category: "Плитка",
        subcategory: "Керамогранит"
    },
    {
        _id: "984549",
        name: "Керамогранит Nature 60*60 baze white глазур 1.44 кв.м./упак",
        availability: "В наличии",
        price: 1375,
        unit: "м.к",
        rate: 4.8,
        brand: "Zerde",
        material: "Гранит",
        color: "Белый",
        category: "Плитка",
        subcategory: "Керамогранит"
    },
    {
        _id: "525400",
        name: "Мозайка LOFT BROWN WOOD MOZAIKA PRA.K. 29.8*29.8см G1",
        availability: "В наличии",
        price: 357,
        unit: "шт",
        rate: 4.8,
        brand: "PARADYZ",
        material: "Керамика",
        color: "Коричневый",
        category: "Плитка",
        subcategory: "Мозайка"
    },
    {
        _id: "748684",
        name: "Мозайка LATERIZIO MOZAIKA CIETA MIX 29.8*29.8",
        availability: "В наличии",
        price: 2197,
        unit: "шт",
        rate: 4.5,
        brand: "PARADYZ",
        material: "Керамика",
        color: "Белый",
        category: "Плитка",
        subcategory: "Мозайка"
    },
    {
        _id: "284503",
        name: "Мозайка ELIA CIETA 29,8*29,8см",
        availability: "В наличии",
        price: 1050,
        unit: "шт",
        rate: 4.4,
        brand: "PARADYZ",
        material: "Керамика",
        color: "Бежевый",
        category: "Плитка",
        subcategory: "Мозайка"
    },
    {
        _id: "208062",
        name: "Праймер (грунтовка битумная) 21,5 л(16 кг) PROFIMAST",
        availability: "В наличии",
        price: 2399,
        unit: "шт",
        rate: 4.4,
        brand: "PROFIMAST",
        material: "Битум",
        color: "Черный",
        category: "Строительные материалы",
        subcategory: "Кровельные материалы"
    },
    {
        _id: "599264",
        name: "Рубероид ТУ РКП-350 (1,0*15 м.) (42 шт. пал) (15мх1)//К- ( кровел)для верх.слоя,П- пылеобразная",
        availability: "В наличии",
        price: 795,
        unit: "рул",
        rate: 4.5,
        brand: "Технониколь",
        material: "Битум",
        color: "Черный",
        category: "Строительные материалы",
        subcategory: "Кровельные материалы"
    },
    {
        _id: "206631",
        name: "Стеклоизол ХКП-3,5 с/холст (9м2) (30шт в поддоне)",
        availability: "Под заказ",
        price: 994,
        unit: "рул",
        rate: 4.8,
        brand: "Технониколь",
        material: "Битум",
        color: "Черный",
        category: "Строительные материалы",
        subcategory: "Кровельные материалы"
    },
    {
        _id: "936489",
        name: "Подоконник ПВХ БАУСЕТ МПР-40/50см/6,0м",
        availability: "Под заказ",
        price: 4260,
        unit: "шт",
        rate: 4.7,
        brand: "ТБМ",
        material: "Пластик",
        color: "Белый",
        category: "Строительные материалы",
        subcategory: "Подоконники"
    },
    {
        _id: "658205",
        name: "Подоконник ПВХ БАУСЕТ МПР-40/10см/6,0м",
        availability: "В наличии",
        price: 850,
        unit: "шт",
        rate: 4.1,
        brand: "ТБМ",
        material: "Пластик",
        color: "Белый",
        category: "Строительные материалы",
        subcategory: "Подоконники"
    },
    {
        _id: "192346",
        name: "Штукатурка КНАУФ Туллер 30 кг (40шт/под)",
        availability: "В наличии",
        price: 418,
        unit: "шт",
        rate: 4.5,
        brand: "KNAUF",
        material: "Гипс",
        color: "Белый",
        category: "Строительные материалы",
        subcategory: "Сухие смеси"
    },
    {
        _id: "161310",
        name: "Самовыравнивающийся наливной пол Boden Turbo, Bergauf 20 кг (64 шт/под)",
        availability: "В наличии",
        price: 323,
        unit: "шт",
        rate: 4.6,
        brand: "bergauf",
        material: "Минеральное вяжущее",
        color: "Светло-серый",
        category: "Строительные материалы",
        subcategory: "Сухие смеси"
    },
    {
        _id: "424725",
        name: "Пескобетон М-300 (ЭТАЛОН) (25кг) (70шт/под)",
        availability: "В наличии",
        price: 180,
        unit: "шт",
        rate: 4.5,
        brand: "Эталон",
        material: "Высококачественный цемент",
        color: "Серый",
        category: "Строительные материалы",
        subcategory: "Сухие смеси"
    },
    {
        _id: "328407",
        name: "Клей для укладки ячеистых блоков Bergauf Kleben Block,ЗИМА 25 кг(56шт/подд)",
        availability: "В наличии",
        price: 295,
        unit: "шт",
        rate: 4.6,
        brand: "bergauf",
        material: "Цементное вяжущее",
        color: "Серый",
        category: "Строительные материалы",
        subcategory: "Сухие смеси"
    },
    {
        _id: "536937",
        name: "Мин.теплоизоляция URSA TERRA 36 PN(1250х610х50) мм 16пл 10 шт/уп 7,62 м2/0,381м3",
        availability: "В наличии",
        price: 1236,
        unit: "упа",
        rate: 4.6,
        brand: "URSA",
        material: "Негорючая минеральная изоляция",
        color: "Желтый",
        category: "Строительные материалы",
        subcategory: "Утеплитель"
    },
    {
        _id: "561513",
        name: "Пенополистирол Техноплекс (1180*580*40мм) (10шт/уп) 35 пл. 0,27376 м3 в уп.",
        availability: "В наличии",
        price: 338,
        unit: "шт",
        rate: 4.8,
        brand: "Техноплекс",
        material: "Пенеполистирол",
        color: "Белый",
        category: "Строительные материалы",
        subcategory: "Утеплитель"
    },
    {
        _id: "404008",
        name: "Энергоизол лавсан 10 мм (1,2*15)рул (18 м2)",
        availability: "В наличии",
        price: 1766,
        unit: "рул",
        rate: 4.2,
        brand: "Энергоизол",
        material: "Лавсан",
        color: "Серебристый",
        category: "Строительные материалы",
        subcategory: "Утеплитель"
    },
    {
        _id: "681189",
        name: `ЭСайдинг (ПВХ).0230.Н. "Тимбер-Блок" Ю-Пласт, Пихта Сахалинская 0,23*3,050м`,
        availability: "Под заказ",
        price: 528,
        unit: "шт",
        rate: 4.3,
        brand: "Ю-Пласт",
        material: "Пластик",
        color: "Коричневый",
        category: "Строительные материалы",
        subcategory: "Сайдинг"
    },
    {
        _id: "566155",
        name: `Сайдинг (ПВХ).0230.Н. "Тимбер-Блок" Ю-Пласт, Пихта Камчатская 0,23*3,050м`,
        availability: "В наличии",
        price: 528,
        unit: "шт",
        rate: 4.3,
        brand: "Ю-Пласт",
        material: "Пластик",
        color: "Коричневый",
        category: "Строительные материалы",
        subcategory: "Сайдинг"
    },
    {
        _id: "340163",
        name: `Сайдинг (ПВХ).0225.Н. "Стоун-Хаус S-LOCK" Ю-Пласт, КЛИНКЕР BALTIC хол.цемент 0,292*1,950м`,
        availability: "В наличии",
        price: 578,
        unit: "шт",
        rate: 4.6,
        brand: "Ю-Пласт",
        material: "Пластик",
        color: "Серый",
        category: "Строительные материалы",
        subcategory: "Сайдинг"
    },
    {
        _id: "939037",
        name: `Сайдинг (ПВХ).0225.Н. "Стоун-Хаус S-LOCK" Ю-Пласт, КЛИНКЕР BALTIC св.медь 0,292*1,950м`,
        availability: "В наличии",
        price: 578,
        unit: "шт",
        rate: 4.6,
        brand: "Ю-Пласт",
        material: "Пластик",
        color: "Бежевый",
        category: "Строительные материалы",
        subcategory: "Сайдинг"
    },
    {
        _id: "715510",
        name: `Герметик силиконовый "Момент" S экспресс белый 280 мл 1120131`,
        availability: "В наличии",
        price: 805,
        unit: "шт",
        rate: 4.8,
        brand: "Момент",
        material: "Силикон",
        color: "Белый",
        category: "Строительные материалы",
        subcategory: "Пена, герметики, клея"
    },
    {
        _id: "464164",
        name: "Монтажная пена Макрофлекс Оригинальная 750мл. стандарт всесезонная",
        availability: "В наличии",
        price: 890,
        unit: "шт",
        rate: 4.7,
        brand: "Макрофлекс",
        material: "Пена",
        color: "Желтый",
        category: "Строительные материалы",
        subcategory: "Пена, герметики, клея"
    },
    {
        _id: "331105",
        name: `Клей "Момент" МОНТАЖ МВп-70 суперсильный прозрачный 185 г Туба`,
        availability: "В наличии",
        price: 315,
        unit: "шт",
        rate: 4.8,
        brand: "Момент",
        material: "Клей",
        color: "Прозрачный",
        category: "Строительные материалы",
        subcategory: "Пена, герметики, клея"
    },
    {
        _id: "475590",
        name: "Стремянка, 3 ступени СИБРТЕХ (стальная) 97843",
        availability: "В наличии",
        price: 1700,
        unit: "шт",
        rate: 4.2,
        brand: " No name",
        material: "Металл",
        color: "Синий",
        category: "Хоз товары",
        subcategory: "Стремянки"
    },
    {
        _id: "391065",
        name: "Стремянка, 3 ступени СИБРТЕХ (стальная) 97843",
        availability: "В наличии",
        price: 2500,
        unit: "шт",
        rate: 4.4,
        brand: " No name",
        material: "Металл",
        color: "Синий",
        category: "Хоз товары",
        subcategory: "Стремянки"
    },
    {
        _id: "407174",
        name: "Стремянка, 4 ступени СИБРТЕХ (стальная) 97844",
        availability: "В наличии",
        price: 2185,
        unit: "шт",
        rate: 4.6,
        brand: " No name",
        material: "Металл",
        color: "Синий",
        category: "Хоз товары",
        subcategory: "Стремянки"
    },
    {
        _id: "830083",
        name: "Мешки (белые) 50*95 1/1000 шт",
        availability: "В наличии",
        price: 24,
        unit: "шт",
        rate: 4.8,
        brand: " No name",
        material: "Ткань",
        color: "Белый",
        category: "Хоз товары",
        subcategory: "Мешки для мусора"
    },
    {
        _id: "714382",
        name: "мешки для мусора (зелёные) 50*90см",
        availability: "В наличии",
        price: 13,
        unit: "шт",
        rate: 4.8,
        brand: " No name",
        material: "Ткань",
        color: "Зеленый",
        category: "Хоз товары",
        subcategory: "Мешки для мусора"
    },
    {
        _id: "836633",
        name: "Грунт DANO GRUNT конц 1:3 (3л)",
        availability: "В наличии",
        price: 608,
        unit: "шт",
        rate: 4.7,
        brand: "DANO",
        material: "Сополимер акриловый",
        color: "Белый",
        category: "Лакакрасочные материалы",
        subcategory: "Грунты"
    },
    {
        _id: "299752",
        name: "Краска интерьерная для стен и потолков моющаяся Основит УНИВИТА Studio LUSSO III база А 9 л",
        availability: "В наличии",
        price: 4774,
        unit: "шт",
        rate: 4.5,
        brand: "Основит",
        material: "Водно-дисперстонный раствор",
        color: "Зеленый",
        category: "Лакакрасочные материалы",
        subcategory: "Краски"
    },
    {
        _id: "284009",
        name: "Эмаль аэрозольная акрил быстросохнущая Deton черный 520 мл",
        availability: "В наличии",
        price: 292,
        unit: "шт",
        rate: 4.4,
        brand: "Deton",
        material: "Водно-дисперстонный раствор",
        color: "Черный",
        category: "Лакакрасочные материалы",
        subcategory: "Эмали"
    },
    {
        _id: "523861",
        name: "Уровень ЛИДЕР 1500 мм ЦИ Л14-1500",
        availability: "Под заказ",
        price: 2666,
        unit: "шт",
        rate: 4.3,
        brand: "ЦИ",
        material: "Пластик",
        color: "Желтый",
        category: "Инструмент",
        subcategory: "Измерительный инструмент"
    },
    {
        _id: "646797",
        name: "Уровень ЛИДЕР 1200 мм ЦИ Л14-1200",
        availability: "В наличии",
        price: 2279,
        unit: "шт",
        rate: 4.7,
        brand: "ЦИ",
        material: "Пластик",
        color: "Желтый",
        category: "Инструмент",
        subcategory: "Измерительный инструмент"
    },
    {
        _id: "247900",
        name: "Штангенциркуль 888, пластмассовый, 150 мм, точность 0,1 мм 101539",
        availability: "В наличии",
        price: 89,
        unit: "шт",
        rate: 4.1,
        brand: "ЦИ",
        material: "Пластик",
        color: "Сине-зеленый",
        category: "Инструмент",
        subcategory: "Измерительный инструмент"
    },
    {
        _id: "256848",
        name: "Рулетка Effecta Nylon 5м/25мм с магн. автостоп, лентой нейлон",
        availability: "В наличии",
        price: 416,
        unit: "шт",
        rate: 4.5,
        brand: "Effecta",
        material: "Пластик",
        color: "Черно-зеленый",
        category: "Инструмент",
        subcategory: "Измерительный инструмент"
    },
    {
        _id: "991531",
        name: "Дрель-Шуруповерт Акк. 18,0В 0-450/1550 об/мин; 1,3 Ач: 1,5ч. рез. накл, кейс 80199",
        availability: "В наличии",
        price: 7270,
        unit: "шт",
        rate: 4.8,
        brand: "FIT",
        material: "Металлопластик",
        color: "Черно-зеленый",
        category: "Инструмент",
        subcategory: "Дрели"
    },
    {
        _id: "271623",
        name: "Дрель ударная, 13мм, реверс, мет корп редукт 0-2800об/мин,0-44800уд/мин,850Вт, ЗУБР ЗДУ-850 ЭРММ2",
        availability: "В наличии",
        price: 5786,
        unit: "шт",
        rate: 4.3,
        brand: "ЗУБР",
        material: "Металлопластик",
        color: "Серо-синий",
        category: "Инструмент",
        subcategory: "Дрели"
    },
    {
        _id: "629745",
        name: "Машина углошлифовальная 180мм, 8000об/мин, 1800Вт ЗУБР УШМ-180-1800 ПМЗ",
        availability: "В наличии",
        price: 6345,
        unit: "шт",
        rate: 4.8,
        brand: "ЗУБР",
        material: "Металлопластик",
        color: "Серо-черный",
        category: "Инструмент",
        subcategory: "Машины углошлифовальные"
    },
    {
        _id: "852709",
        name: "Киянка фибергласовая обрезин. ручка. 450 г 48 Китай 3304012",
        availability: "В наличии",
        price: 321,
        unit: "шт",
        rate: 4.0,
        brand: "ЗУБР",
        material: "Металлопластик",
        color: "Черно-синий",
        category: "Инструмент",
        subcategory: "Столярно-слесарный инструмент "
    },
    {
        _id: "339564",
        name: `Клещи переставные "Стандарт" тип А2 250 мм 70625`,
        availability: "В наличии",
        price: 629,
        unit: "шт",
        rate: 4.4,
        brand: "ЗУБР",
        material: "Металлопластик",
        color: "Черно-красный",
        category: "Инструмент",
        subcategory: "Столярно-слесарный инструмент "
    },
    {
        _id: "709860",
        name: `Отвертка "Универсал" CrV сталь, прорезиненная ручка, Профи 5*150 мм PH1 55107`,
        availability: "В наличии",
        price: 181,
        unit: "шт",
        rate: 4.7,
        brand: "ЗУБР",
        material: "Металлопластик",
        color: "Синий, красный",
        category: "Инструмент",
        subcategory: "Столярно-слесарный инструмент "
    },
    {
        _id: "999737",
        name: "Панель светодиодная LPU-02 36Вт ПРИЗМА 230В 4000К 3420 Лм 595х595х19мм белая IP40 IN HOME",
        availability: "В наличии",
        price: 648,
        unit: "шт",
        rate: 4.6,
        brand: "IN HOME",
        material: "Металлопластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Внутреннее освещение"
    },
    {
        _id: "536964",
        name: "Спот на гибком основании СГС-02, 3 Вт, COB, 270 лм, 4000 К, IP20, Эрика, с выкл., черный, TDM",
        availability: "В наличии",
        price: 1017,
        unit: "шт",
        rate: 4.9,
        brand: "TDM",
        material: "Металлопластик",
        color: "Черный",
        category: "Освещение",
        subcategory: "Внутреннее освещение"
    },
    {
        _id: "648676",
        name: "Светильник Feron CD5023 20LED*2835 SMD 4000K 15W GX53, без лампы, белый мат. хром (круг) 40522",
        availability: "В наличии",
        price: 398,
        unit: "шт",
        rate: 5.0,
        brand: "FERON",
        material: "Пластик и стекло",
        color: "Белый",
        category: "Освещение",
        subcategory: "Внутреннее освещение"
    },
    {
        _id: "900757",
        name: "Комплект светодиодной ленты SMD2835-60 LED/м-12 В-4,8 Вт/м-IP65-3000 К (5 м), 24 Вт TDM SQ0331-0229",
        availability: "Под заказ",
        price: 1204,
        unit: "шт",
        rate: 4.0,
        brand: "TDM",
        material: "Пластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Внутреннее освещение"
    },
    {
        _id: "733496",
        name: `Светильник Спот, 4х40Вт, Е14, 230 В, 50 Гц, IP20, "Бутон", планка, ЭКО, сосна, TDM SQ0356-0005`,
        availability: "В наличии",
        price: 3218,
        unit: "шт",
        rate: 4.5,
        brand: "TDM",
        material: "Металл и стекло",
        color: "Серебро",
        category: "Освещение",
        subcategory: "Внутреннее освещение"
    },
    {
        _id: "351747",
        name: "Светодиодный прожектор SAFFIT SFL90-50 IP65 50W 4000K черный 55077",
        availability: "В наличии",
        price: 404,
        unit: "шт",
        rate: 4.5,
        brand: "Saffit",
        material: "Металл и стекло",
        color: "Черный",
        category: "Освещение",
        subcategory: "Наружнее освещение"
    },
    {
        _id: "629163",
        name: "Светодиодный светильник LED ДПП 2801 12Вт 990 лм 4000К IP65 белый овал 200*100*46 мм SQ0329-0813",
        availability: "В наличии",
        price: 500,
        unit: "шт",
        rate: 4.7,
        brand: "TDM",
        material: "Металл и стекло",
        color: "Белый",
        category: "Освещение",
        subcategory: "Наружнее освещение"
    },
    {
        _id: "232371",
        name: "Светильник НПБ 1102 белый/круг с реш. 100 Вт IP54 TDM SQ0303-0026",
        availability: "В наличии",
        price: 588,
        unit: "шт",
        rate: 4.3,
        brand: "TDM",
        material: "Металл и стекло",
        color: "Белый",
        category: "Освещение",
        subcategory: "Наружнее освещение"
    },
    {
        _id: "221087",
        name: "Лампа светодиодная Feron LB-454 GX53 15W 4000K 25836",
        availability: "В наличии",
        price: 145,
        unit: "шт",
        rate: 4.9,
        brand: "FERON",
        material: "Пластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Лампы"
    },
    {
        _id: "633213",
        name: "Лампа светодиодная Feron. PRO шар LB-1407 7.5W 650Lm 230V E27 4000K G45 OSRAM LED 38075",
        availability: "В наличии",
        price: 128,
        unit: "шт",
        rate: 4.8,
        brand: "FERON",
        material: "Пластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Лампы"
    },
    {
        _id: "510128",
        name: "Лампа светодиодная Feron. PRO свеча LB-1307 7.5W 650Lm 230V E27 4000K C37 OSRAM LED 38057",
        availability: "В наличии",
        price: 143,
        unit: "шт",
        rate: 4.7,
        brand: "FERON",
        material: "Пластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Лампы"
    },
    {
        _id: "637667",
        name: "Лампа светодиодная свеча Saffit SBC3709 9W 2700K 230V E14 C37 1/10/200 55078",
        availability: "В наличии",
        price: 84,
        unit: "шт",
        rate: 4.7,
        brand: "Saffit",
        material: "Пластик",
        color: "Белый",
        category: "Освещение",
        subcategory: "Лампы"
    },
    {
        _id: "916249",
        name: "Лампа галогеновая 35W 220V G5.3 NAVIGATOR 128301/94205",
        availability: "В наличии",
        price: 80,
        unit: "шт",
        rate: 4.0,
        brand: "Navigator",
        material: "Стекло",
        color: "Прозрачный",
        category: "Освещение",
        subcategory: "Лампы"
    },
    {
        _id: "694504",
        name: "Гвозди 3,5*90 (1,0кг) 3229",
        availability: "В наличии",
        price: 165,
        unit: "упа",
        rate: 4.0,
        brand: "ксв",
        material: "Металл",
        color: "Серый",
        category: "Крепеж",
        subcategory: "Гвозди"
    },
    {
        _id: "905291",
        name: "Гвозди 4,0*100 (1,0кг) 3237",
        availability: "В наличии",
        price: 165,
        unit: "упа",
        rate: 4.0,
        brand: "ксв",
        material: "Металл",
        color: "Серый",
        category: "Крепеж",
        subcategory: "Гвозди"
    },
    {
        _id: "103234",
        name: "Дюбель рамный МF 8*92 (100шт)",
        availability: "В наличии",
        price: 14,
        unit: "шт",
        rate: 4.5,
        brand: "ксв",
        material: "Металл",
        color: "Серый",
        category: "Крепеж",
        subcategory: "Дюбели"
    },
    {
        _id: "508699",
        name: "Дюбель для изоляции 10х160 IZO (500 шт) с пласт. гвоздем",
        availability: "В наличии",
        price: 5,
        unit: "шт",
        rate: 4.5,
        brand: "ксв",
        material: "Пластик",
        color: "Белый",
        category: "Крепеж",
        subcategory: "Дюбели"
    },
    {
        _id: "947907",
        name: "Шуруп кров. оцинк. КР с ZP 5.5*19 RAL6005 темно-зеленый (50 шт)",
        availability: "В наличии",
        price: 168,
        unit: "упа",
        rate: 4.8,
        brand: "СтройБат",
        material: "Металл",
        color: "Зеленый",
        category: "Крепеж",
        subcategory: "Шурупы"
    },
    {
        _id: "627428",
        name: "шуруп универсальный белый 4х60 (4000шт, 5000шт, 4500шт)",
        availability: "В наличии",
        price: 1,
        unit: "шт",
        rate: 4.9,
        brand: "СтройБат",
        material: "Металл",
        color: "Серый",
        category: "Крепеж",
        subcategory: "Шурупы"
    },
    {
        _id: "369165",
        name: "шуруп универсальный желтый 5х60 (3000шт,2500шт)",
        availability: "В наличии",
        price: 2,
        unit: "шт",
        rate: 4.8,
        brand: "СтройБат",
        material: "Металл",
        color: "Золотистый",
        category: "Крепеж",
        subcategory: "Шурупы"
    }
];
const fetchAll = () =>
    new Promise((resolve) => {
        window.setTimeout(function () {
            resolve(products);
        }, 2000);
    });

const getById = (id) =>
    new Promise((resolve) => {
        window.setTimeout(function () {
            resolve(products.find((product) => product._id === id));
        }, 1000);
    });

export default {
    fetchAll,
    getById
};

/* if (!localStorage.getItem("users")) {
    localStorage.setItem("users", JSON.stringify(users));
}

const fetchAll = () =>
    new Promise((resolve) => {
        window.setTimeout(function () {
            resolve(JSON.parse(localStorage.getItem("users")));
        }, 2000);
    });
const update = (id, data) =>
    new Promise((resolve) => {
        const users = JSON.parse(localStorage.getItem("users"));
        const userIndex = users.findIndex((u) => u._id === id);
        users[userIndex] = { ...users[userIndex], ...data };
        localStorage.setItem("users", JSON.stringify(users));
        resolve(users[userIndex]);
    });

const getById = (id) =>
    new Promise((resolve) => {
        window.setTimeout(function () {
            resolve(
                JSON.parse(localStorage.getItem("users")).find(
                    (user) => user._id === id
                )
            );
        }, 1000);
    }); */
